apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ascendly-ingress
spec:
  rules:
    - host: ascendly.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ascendly-web
                port:
                  number: 3000
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: ascendly-api
                port:
                  number: 8000
