"use client";

import { useEffect, useState } from "react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { apiFetch } from "@/lib/api-client";

interface Summary {
  segment: string;
  churn_risk_users: number;
  active_subscriptions: number;
  top_category: string;
  recent_30_day_revenue: number;
  llm_summary: string;
  llm_source: string;
  recommendation: string;
  content_gap: string;
  timestamp: string;
}

interface Forecast {
  next_30_days: {
    predicted_revenue: number;
    predicted_new_subscriptions: number;
    predicted_churn_rate: number;
    confidence: number;
  };
  churn_risk_users: number;
  note: string;
}

export default function AIAnalyticsPage() {
  const [summary, setSummary] = useState<Summary | null>(null);
  const [forecast, setForecast] = useState<Forecast | null>(null);
  const [error, setError] = useState("");

  useEffect(() => {
    apiFetch("/admin/analytics/summary")
      .then(setSummary)
      .catch((e) => setError(e.message));
  }, []);

  const runForecast = async () => {
    setError("");
    try {
      const f = await apiFetch("/admin/analytics/forecast");
      setForecast(f);
    } catch (e: any) {
      setError(e.message);
    }
  };

  return (
    <section className="py-12">
      <div className="mx-auto max-w-page px-6">
        <h1 className="text-3xl font-semibold text-primary-900">AI Analytics & Forecasting</h1>
        <div className="mt-6 grid gap-4 md:grid-cols-2">
          <Card className="p-5">
            <h2 className="font-medium text-neutral-900">Summary</h2>
            {summary ? (
              <div className="mt-3 space-y-3 text-sm text-neutral-900">
                <p>{summary.llm_summary}</p>
                <ul className="space-y-1 text-neutral-600">
                  <li><strong>Segment:</strong> {summary.segment}</li>
                  <li><strong>Churn risk users:</strong> {summary.churn_risk_users}</li>
                  <li><strong>Active subscriptions:</strong> {summary.active_subscriptions}</li>
                  <li><strong>Top category:</strong> {summary.top_category}</li>
                  <li><strong>30-day revenue:</strong> ${summary.recent_30_day_revenue.toLocaleString()}</li>
                </ul>
                <p className="text-xs text-neutral-500">Generated by {summary.llm_source}</p>
              </div>
            ) : (
              <p className="mt-3 text-sm text-neutral-600">Loading...</p>
            )}
          </Card>
          <Card className="p-5">
            <h2 className="font-medium text-neutral-900">30-Day Forecast</h2>
            <p className="mt-3 text-sm text-neutral-600">
              Run the forecasting pipeline to predict next 30-day revenue, churn risk, and content demand.
            </p>
            <Button onClick={runForecast} className="mt-4">Run forecast</Button>
            {forecast && (
              <div className="mt-4 space-y-3 text-sm text-neutral-900">
                <ul className="space-y-1">
                  <li><strong>Predicted revenue:</strong> ${forecast.next_30_days.predicted_revenue.toLocaleString()}</li>
                  <li><strong>New subscriptions:</strong> {forecast.next_30_days.predicted_new_subscriptions}</li>
                  <li><strong>Churn rate:</strong> {(forecast.next_30_days.predicted_churn_rate * 100).toFixed(1)}%</li>
                  <li><strong>Churn risk users:</strong> {forecast.churn_risk_users}</li>
                  <li><strong>Confidence:</strong> {(forecast.next_30_days.confidence * 100).toFixed(0)}%</li>
                </ul>
                <p className="text-xs text-neutral-500">{forecast.note}</p>
              </div>
            )}
            {error && <p className="mt-3 text-sm text-error">{error}</p>}
          </Card>
        </div>
      </div>
    </section>
  );
}
